name: educational_app
description: A Flutter educational app for course management
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9  # For state management
  cached_network_image: ^3.3.0  # For better image handling
  intl: ^0.18.1  # For internationalization

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  very_good_analysis: ^5.1.0  # Additional lint rules

flutter:
  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true